### ISSUE TITLE
Plugin not working with woo 3.1.2

### ISSUE THREAD

**Issue by bogdanhruban** [SantiagoInteractive/mobilpay-card-gateway-for-woocommerce#4]
When an order is placed for credit card payment, there is no redirect to the mobilpay website, it just redirects to some kind of order complete page with the message that there is a payment due. 

````

PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/shop.lifeinbalance.ro/wp-content/plugins/mobcard-woo-payment-gateway/includes/request/class-mobilpay-card.php:33
Stack trace:
#0 /var/www/shop.lifeinbalance.ro/wp-content/plugins/mobcard-woo-payment-gateway/includes/request/class-mobilpay-abstract.php(205): Mobilpay_Payment_Request_Card->_prepare()
#1 /var/www/shop.lifeinbalance.ro/wp-content/plugins/mobcard-woo-payment-gateway/mobcard-woo-payment-gateway.php(315): Mobilpay_Payment_Request_Abstract->encrypt('/var/www/shop.l...')
#2 /var/www/shop.lifeinbalance.ro/wp-content/plugins/mobcard-woo-payment-gateway/mobcard-woo-payment-gateway.php(119): WC_Mobilpay_Card->generate_mobilpay_card_form(593)
#3 /var/www/shop.lifeinbalance.ro/wp-includes/class-wp-hook.php(298): WC_Mobilpay_Card->mobilpay_receipt_page(593)
#4 /var/www/shop.lifeinbalance.ro/wp-includes/class-wp-hook.php(323): WP_Ho

````

**Comment by bogdanhruban** [comment]
Most probably a server error on my side .. :( sorry for the spam.
